export const projects = [
    {
        id: 1,
        imgLink: "https://baby-yelp.herokuapp.com",
        img: "../../../img/project2-ss.png",
        alt: "Baby Yelp Screenshot",
        title: "Baby Yelp",
        text: "Application that allows the user to search for restaurants and write reviews.",
        github: "https://github.com/BennetWilson/baby-yelp",
    },
    {
        id: 2,
        imgLink: "https://note-taker129.herokuapp.com/notes",
        img: "../../../img/note-taker-ss2.png",
        alt: "Note Taker Screenshot",
        title: "Note Taker",
        text: "Allows the user to write, save and delete notes in an application similar to the notes app on your smartphone.",
        github: "https://github.com/jacobluedke/note-taker",
    },
    {
        id: 3,
        imgLink: "https://github.com/Tgarrey37/super-team-project",
        img: "../../../img/project1-ss.png",
        alt: "Travel Planner Screenshot",
        title: "Travel Planner",
        text: "This application allows the user to search a location to find local weather, hotels, restaurants, and attractions.",
        github: "https://tgarrey37.github.io/super-team-project",
    },
    {
        id: 4,
        imgLink: "https://jacobluedke.github.io/day-planner/",
        img: "../../../img/day-planner-ss.png",
        alt: "Day Planner Screenshot",
        title: "Day Planner",
        text: "This application allows the user to write, save and delete important information into different hour time slots throughout a 9-5 work day.",
        github: "https://github.com/jacobluedke/day-planner",
    },
    {
        id: 5,
        imgLink: "https://watch.screencastify.com/v/zYMBntxU1pz3evCr4Sop",
        img: "../../../img/social-network-ss.png",
        alt: "Social Network API Screenshot",
        title: "Social Network API Back-End",
        text: "This is a back-end application that allows the user to write, update, and delete posts/comments as well as add and delete friends.",
        github: "https://github.com/jacobluedke/social-network-api",
    },
    {
        id: 6,
        imgLink: "https://watch.screencastify.com/v/0XHGKljEIeEx2lZdWuOq",
        img: "../../../img/project2-ss.png",
        alt: "E-Commerce Screenshot",
        title: "E-Commerce Back-End",
        text: "Application that allows the user to add, update and delete products, categories and tags for an e-commerce webpage.",
        github: "https://github.com/BennetWilson/baby-yelp",
    },
]